POST https://accounts.spotify.com/api/token 
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=17ec561e961c4ad2b11a5285ce1b0cdf&client_secret=b8c0aefe05c749dfa6e7e1d185c3dbdf
###

GET https://api.spotify.com/v1/search?q=bellofigo&type=artist 
Authorization: Bearer BQA8JbL_mCW-ccDX0AnuMyztI9dihOao-Z3nyHyzlPsLmQb428aNhEb6ofYZ5fuQ4bmNkmqLHkJVm7YiN7I54yBNVYSFeO4ehRclXVJgI59Rz00A2S3zDefrOISdQZ3dpVEmh7-Ymu4'
###

GET https://api.spotify.com/v1/artists/1dfeR4HaWDbWqFHLkxsg1d
Authorization: Bearer BQA8JbL_mCW-ccDX0AnuMyztI9dihOao-Z3nyHyzlPsLmQb428aNhEb6ofYZ5fuQ4bmNkmqLHkJVm7YiN7I54yBNVYSFeO4ehRclXVJgI59Rz00A2S3zDefrOISdQZ3dpVEmh7-Ymu4