POST https://accounts.spotify.com/api/token 
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=17ec561e961c4ad2b11a5285ce1b0cdf&client_secret=b8c0aefe05c749dfa6e7e1d185c3dbdf
###

GET https://api.spotify.com/v1/search?q=bellofigo&type=artist 
Authorization: Bearer BQBL7DkZX3byn2HPLFVT_GArqRnOFYalrKZZ2sxKkXtNwd57MbGBO7xJ4nRrKoyemvFQc2MeFOuY1jgRKP03mac8CdITULal9N9bKT3Nkwwsi7ebPja2IPL_CP_5tdG3dCc2_jCHEAg'